# Generated by Django 3.1 on 2021-07-28 18:05

import FarmTest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=FarmTest.models.PasswordModelField(max_length=100, null=True, verbose_name='confirm Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email Address'),
        ),
    ]
