# Generated by Django 3.1 on 2021-07-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmTest', '0002_auto_20210728_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
